# 
#  The `.config/wallpapers/` directory contains a handful 
#  of wallpapers that I find to fit best with this theme.
# 
preload = ~/dotfiles/user/wallpapers/active.jpg
wallpaper = ~/dotfiles/user/wallpapers/active.jpg

splash = false
